version: "3.5"

volumes:
  db:

services:
  db:
    image: "postgres:15.3-alpine"
    restart: always
    volumes:
      - "db:/data/postgres"
    ports:
      - $PORT:$PORT
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB